### ISSUE TITLE
Parallels desktop "the virtual machine processor was reset by the operating system"

### ISSUE THREAD

**Issue by MiMillieuh** [AMD-OSX/bugtracker#104]
Hello everyone ^^

So I have an error with parallels desktop : 
Each time I start a vm my hackintosh start to lag and I have this message : "the virtual machine processor was reset by the operating system"
I use a ryzen 7 2700x on catalina with opencore
SVM is enable in my bios 
If someone know how to fix it ^^
![Capture d’écran 2020-10-16 à 23 19 07](https://user-images.githubusercontent.com/52078885/96309843-637e4580-1006-11eb-99da-e78afec62e6f.png)

**Comment by HoshiYamazaki** [comment]
Parallels 14-16 and VMware 11-12 will not work. You have to use VirtualBox or VMware 10...

**Comment by alyxferrari** [comment]
As @HoshiYamazaki said, use Parallels 13.1.0, VMware 10, or VirtualBox.
