### ISSUE TITLE
Kernel patch not found result 3 and result 24

### ISSUE THREAD

**Issue by NotTheEnclave** [AMD-OSX/bugtracker#106]
**Describe the bug**
00:000 00:000 OC: Kernel patcher result 3 for kernel (algrey - cpuid_set_cache_info - cpuid 0x8000001D instead 0) - Not Found
00:456 00:456 OC: Kernel patcher result 24 for kernel (algrey - tsc_init - remove Penryn check to execute default case 10.14.1-.3) - Not Found

Installer ran fine, but booting into the newly installed drive results in a black screen. The above was in the open core EFI.

**To Reproduce**

**Expected behavior**
Black screen

**Screenshots**

**System Version (please complete the following information):**
 - macOS: 10.14.6
 

**System Information (please complete the following information):**
 - CPU - Ryzen 7 3700X
 - Motherboard - Asus AM4 TUF Gaming X570-Plus
 - GPU - Sapphire RX580 8GB
 - Bootloader - opencore 0.6.2

**Additional context**
This issue happened before, """"3, 7, 29 ,31 kernel patch not found #36""" similar but not only kernel patch 3 but 24 as well. 

EDIT: I was dumb and left my second graphics card, a GT520 in the second PCIE port. Took it out, now everything works fine. Lessons have been learned.

**Comment by CannonFox** [comment]
I have same problem. But i have 1 gpu - rx 5500xt
What should I do? I cant do anything
