### ISSUE TITLE
Arch key missing from AMD_Vanilla/17h_19h/patches.plist -> Kernel -> Patch algrey cpuid_set_cache_info

### ISSUE THREAD

**Issue by andistern** [AMD-OSX/bugtracker#108]
* Guide(s) in question
patches.plist, 
( cosmetic )
Line 254, 289 and more
* Link to page(s) with the issue
https://github.com/AMD-OSX/AMD_Vanilla/blob/opencore/17h_19h/patches.plist
* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
accuracy / reliability of documentation ? 
* Include possible fixes
just insert appropriate lines _if applicable_, to show uniform appearance of patches:
```
				<key>Arch</key>
				<string>Any</string>
```
regards

**Comment by alyxferrari** [comment]
Closing as this is a cosmetic issue and isn't present in the current patches.

**Comment by andistern** [comment]
anybody caring about appearance & uniformity?
