### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by avvink** [AMD-OSX/bugtracker#110]
I tried updating from 11.2 Beta to 11.3 on the latest version of open core, beforehand I setup a new clean EFI setup with 0.6.6. 11.2 is still working great. I think it's missing kernel patches for `CPUFAMILY_INTEL_PENRYN`. Attached
[opencore-2021-02-03-094853.txt](https://github.com/AMD-OSX/bugtracker/files/5918937/opencore-2021-02-03-094853.txt)
 is the log:

**System Version:**
 - macOS: 11.3 Beta

**System Information**
 - AMD Ryzen 3950x
 - Msi x570 unify
 - amd rx 5500 xt
 - OC 0.6.6

**Comment by Shaneee** [comment]
Known issue. Patches need reworked. An update will be pushed to the GitHub when we have it.

**Comment by Shaneee** [comment]
@avvink An update has been pushed, https://github.com/AMD-OSX/AMD_Vanilla/commit/454ec67c181aaed9e92c53c7b2e2325ec62bbf13
