### ISSUE TITLE
Sidecar can't run correctly.

### ISSUE THREAD

**Issue by dg-w36** [AMD-OSX/bugtracker#13]
I upgrade my ryzen hackintosh from Mojave(10.14.6) to the Catalina(10.15.0) and it work well.
I want to test the Sidecar. It can run, but only show black screen on my iPad (Ipad mini 5). I google this problem and find some people said that the Sidecar needs Intel iGPU(https://www.reddit.com/r/hackintosh/comments/dbvm04/hackintosh_ipad_sidecar/) . Anyone have some ideas to fix this problem?
My hardware and settings are :
    CPU: 3700x
    Motherboard: B450
    GPU: Vega 56 
    SMBIOS: iMacPro1,1
kexts file: Lilu Whatevergreen

**Comment by alyxferrari** [comment]
The current "solution" for Sidecar on AMD is using an iMac19,x or iMac20,x SMBIOS, installing [FeatureUnlock.kext](https://github.com/acidanthera/FeatureUnlock), and running the command in the FeatureUnlock README.
