### ISSUE TITLE
AMD Radeon ProRender hangs Blender 2.8 

### ISSUE THREAD

**Issue by zalivar71** [AMD-OSX/bugtracker#14]
If try to add AMD Radeon ProRender add-on to Blender  - application hang up.

My config:
CPU AMD Ryzen 7 1800X
GPU AMD Radeon RX 580

<img width="654" alt="screen1" src="https://user-images.githubusercontent.com/54080051/62969364-c928dd80-be15-11e9-9c85-d2eb06750161.png">

**Comment by alyxferrari** [comment]
Closing as Blender 3.1 adds Metal support, removing the need for ProRender.
