### ISSUE TITLE
A Sound card‘s Problem on my Ryzen 3 2200g & B350M Mortar

### ISSUE THREAD

**Issue by WtXeLd** [AMD-OSX/bugtracker#2]
I'm sorry to bother you Developers.

When I upgrade Mojave 10.14.1 to 10.14.5, I trans the way replace Kernel  to this AMC_Vanilla.
Now my sound card have a problem, it has crackling noise frequently and can't fix, but it's good before.
（and I had tried to reinstall 10.14.1 with Vanilla, the sound card crackling too.）

I try to build AppleALC with my codec and inject layout-id and replace VooooHDA and re-install system, but no effect.

And I found many people, who use the 2200g like me, meet the same problem on sound card.

So I want to ask for help, whether you can find reason and fix it, and whether I need to do something to coordinate you Developers ?

Looking forward to your reply, and thanks very very much!

**Comment by plamenh** [comment]
Same issue on 3200g (unsurprising, given it’s a rebranded 2200g). The js script almost solves it.

**Comment by caem1420** [comment]
Same Issue on amd 5 3400g Tried to overclocking no fix, @cosier can you show the Node JS script please

**Comment by ranahan** [comment]
> Same Issue on amd 5 3400g Tried to overclocking no fix, @cosier can you show the Node JS script please

same CPU. running catalina 10.15.7... :(

**Comment by caem1420** [comment]
@ranahan https://github.com/astrihale/1plus1-audio-fix

**Comment by RogellParadox** [comment]
I also have got a problem with that. I notice 70% of times I keep moving my mouse the crackling goes away.
As far as I was told, the problem is with the AMD G-series. We need more people with both G-series and non-G-series to test it.

**Comment by astrihale** [comment]
I created a user friendly version of the `1plus1-audio-fix` script.
You could give it a shot maybe:
https://github.com/astrihale/speedkeeper

**Comment by alyxferrari** [comment]
Either use a USB sound card, which will completely fix the audio issue, or try the [Speedkeeper](https://github.com/astrihale/speedkeeper) app if you don't have a USB sound card.

**Comment by leonsp95** [comment]
> Either use a USB sound card, which will completely fix the audio issue, or try the [Speedkeeper](https://github.com/astrihale/speedkeeper) app if you don't have a USB sound card.

Speedkeeper didn't help at all for me.
I'm trying the USB card later and will update this comment if it works.

**Comment by alyxferrari** [comment]
Yeah Speedkeeper works completely for some, partially for some, and just doesn't work at all for others. It's very hit or miss.

**Comment by alyxferrari** [comment]
Also make sure you have SSDT-USBX and a USB map.

**Comment by aluveitie** [comment]
Speedkeeper needs to put enough load to prevent the CPU from down clocking. The slower the CPU, the better that would work.

**Comment by leonsp95** [comment]
> Speedkeeper needs to put enough load to prevent the CPU from down clocking. The slower the CPU, the better that would work.

I imagined so.
Btw the usb card and didn't have much luck. The best fix is really changing the CPU. Or either moving the mouse intermitently

**Comment by aluveitie** [comment]
The USB sound card needs its own timer, otherwise it will have the same issue.
