### ISSUE TITLE
Still slow 3D performance in Games in macOS with AMD cpus

### ISSUE THREAD

**Issue by tomnic79** [AMD-OSX/bugtracker#5]
CPU: AMD Ryzen R9 3950X
GPU: AMD XFX Radeon VII 16Gb HBM2
macOS version: Catalina 10.15.4
15h/16h or 17h: 17h patches in "real" mode (OC 0.5.8)
I am using and can reproduce on the latest patches: Yes

Hi everybody, can we find a way to boost the 3d performance with AMD cpus and macOS? 

I know that kernel patches are slowing down those performances... in fact if I try Proxmox (so no patches, OC 0.5.8) with my setup I can get 30% more 3d performance (eg. CineBench 15 OpenGL test) and really faster rendering in Xonotic benchmark (min fps is 15, with patches I get 5 as minimum).

Can anybody update those 17h patches? Is there any way to fix this poor 3D performance other than running Proxmox?

**Comment by reaper69man** [comment]
I'm also experiencing poor graphical performance on my newly built AMD 3950X Hackintosh with a Radeon VII when compared to my Intel 7980XE Hackintosh which also has a Radeon VII.  The UI on the AMD system just doesn't feel quite as fluid and 3D performance is approx. 50% of my Intel System.  Although, GPU compute performance between the two systems is comparable:

Geekbench (Metal): AMD - 103639 / Intel - 96146
Geekbench (OpenGL): AMD - 56890 / Intel - 82626
Luxmark: AMD - 50117 / Intel - 50117
Heaven (Extreme): AMD - 58.0fps / Intel 116.7fps

I've also noticed the following error being logged very sporadically on the AMD system:

localhost kernel[0]: (IOAcceleratorFamily2) void IOAccelFenceMachine::fence_timeout(IOTimerEventSource *): AMDRadeonAccelerator prodding blockFenceInterrupt

**Comment by HoshiYamazaki** [comment]
Yeah, and I want to note that FF XIV performance on my Windows boot is about 60 FPS on 4K maxed, and on Hackintosh it's 30FPS FullHD mid. 

![image](https://user-images.githubusercontent.com/21007545/86594928-2e3e7200-bf98-11ea-88b2-661b309c455a.png)

Some people were saying that I'm not running real mac and this is an cause, but I see this as some kind of misunderstanding. Basically Intel Hackintoshes /outperforms/ real Macs anyway and you can /game/ on them /easily/. Also you CAN'T notice 500% performance drop while using macOS on Ryzentosh, this is just unreal. The issue is somewhere in drivers, maybe 10.15.6 will fix the problem, but I don't have time to test beta 3 on my machine and then revert back. I don't know also if people tested Big Sur, and it's better or not.

Something is also different when running Hack in Proxmox VM, I suppose the issue is in kernel patches, or there is some difference beetwen native and VFIO passthrought support of Radeon.

**Comment by Pavo-IM** [comment]
Just wanted to add here that the patch that is causing GPU performance issues is the Fix PAT kernel patch.

**Comment by tomnic79** [comment]
Tried to disable the Fix Pat kernel patch as Pavo-IM suggested, my system booted without yellow screen, it's very slow in the GUI in the first three minutes but it boots, Cinebench OpenGL score went up to promox levels ( 130 fps vs 100 fps), in Minecraft also I get 300 fps, but I get horrible graphical glitches... I think that fixing mtrr_update_action in xnu for AMD is the key to solve the issue I've opened here

**Comment by tomnic79** [comment]
Yellow screen fixed and performance boosted A LOOOOT using this replace value in Fix Pat patch:

`<data>uXcCAAC4BgYGBroGBgYGDzAPCQ==</data>`

**Comment by tomnic79** [comment]
Solved disabling the Fix Pat patch for TRX40 users. For every other AMD user you just need to change the replace value of the Fix Pat patch as follows:

`<data>uXcCAAC4BgYGBroGBgYGDzAPCQ==</data>`

I've done a video with direct comparison with the old and the new patch: https://www.youtube.com/watch?v=6r-d4jgnc2E

**Comment by erenatas** [comment]
> As Pavo said, problem solved disabling the Fix Pat patch for TRX40 users, but for every other AMD user you just need to change the replace value of the Fix Pat patch as follows:
> 
> `<data>uXcCAAC4BgYGBroGBgYGDzAPCQ==</data>`
> 
> I've done a video with direct comparison with the old and the new patch: https://www.youtube.com/watch?v=6r-d4jgnc2E

I'm currently giving this a shot. Geekbench 5 OpenCL went from 44k to 50k. Thanks!

**Comment by aleixsr** [comment]
Hello, this fix works like a charm!
What I find when I changed from "uXcCAAC4BgEHALoGAQcADx9AAA==" to "uXcCAAC4BgYGBroGBgYGDzAPCQ==" gived me x10 FPS!

But I found a cons: Sound output only on DisplayPort is "glitching", do you know why?

Thank you very much.

**Comment by tomnic79** [comment]
It's a "secondary" bug with some configurations, try to open audio/midi utility and adjust sample rate / bit rate of DP audio

**Comment by aleixsr** [comment]
Hi, I tried Audio MIDI Setup but it didn't help, do you have any idea?

**Comment by mame-erl** [comment]
> As Pavo said, problem solved disabling the Fix Pat patch for TRX40 users, but for every other AMD user you just need to change the replace value of the Fix Pat patch as follows:
> 
> `<data>uXcCAAC4BgYGBroGBgYGDzAPCQ==</data>`
> 

Can confirm this highly increasing 3D performance on my 10.15.7 / Ryzen 7 3700X / Sapphire RX5600XT Hackintosh. Thank you!

**Comment by aleixsr** [comment]
Yes I can confirm competely.

**Comment by W-KE** [comment]
> As Pavo said, problem solved disabling the Fix Pat patch for TRX40 users, but for every other AMD user you just need to change the replace value of the Fix Pat patch as follows:
> 
> `<data>uXcCAAC4BgYGBroGBgYGDzAPCQ==</data>`
> 
> I've done a video with direct comparison with the old and the new patch: https://www.youtube.com/watch?v=6r-d4jgnc2E

Confirmed fix working and no issue with DP audio after applying `Shaneee - mtrr_update_action - fix PAT`

Got around 25fps with `algrey - mtrr_update_action - fix PAT` and around 300fps with `Shaneee - mtrr_update_action - fix PAT` in Minecraft.

Should get `Shaneee - mtrr_update_action - fix PAT [my default] : Full FPS on gaming but issues using HDMI/DP audio.`
But I haven't got any audio issue with DP.

Component | Model
-- | --
CPU | AMD Ryzen 9 3900X
RAM | 64GB (2 x 32GB) DDR4 @2666MHz CL16
Mobo | ROG Strix X570-E Gaming
Graphics | GIGABYTE Radeon™ RX 5700 XT 8G Reference
OC | 0.6.3

**Comment by GabSan1212** [comment]
> Hello, this fix works like a charm! What I find when I changed from "uXcCAAC4BgEHALoGAQcADx9AAA==" to "uXcCAAC4BgYGBroGBgYGDzAPCQ==" gived me x10 FPS!
> 
> But I found a cons: Sound output only on DisplayPort is "glitching", do you know why?
> 
> Thank you very much.

How u changed it?

**Comment by aleixsr** [comment]
> > Hello, this fix works like a charm! What I find when I changed from "uXcCAAC4BgEHALoGAQcADx9AAA==" to "uXcCAAC4BgYGBroGBgYGDzAPCQ==" gived me x10 FPS!
> > But I found a cons: Sound output only on DisplayPort is "glitching", do you know why?
> > Thank you very much.
> 
> How u changed it?

Using ProperTree is the easyest way.

**Comment by GabSan1212** [comment]
![image](https://github.com/AMD-OSX/bugtracker/assets/159416189/51514c9a-8d1a-4023-8b3d-feec3a0b8673)
what option I need to change?

**Comment by GabSan1212** [comment]
> > > Hello, this fix works like a charm! What I find when I changed from "uXcCAAC4BgEHALoGAQcADx9AAA==" to "uXcCAAC4BgYGBroGBgYGDzAPCQ==" gived me x10 FPS!
> > > But I found a cons: Sound output only on DisplayPort is "glitching", do you know why?
> > > Thank you very much.
> > 
> > 
> > How u changed it?
> 
> Using ProperTree is the easyest way.

![image](https://github.com/AMD-OSX/bugtracker/assets/159416189/e642587b-d375-4ebd-8c44-612eb77663e8)
what option I need to change here

**Comment by aleixsr** [comment]
Change Enabled to True at #20 and Enabled to False at #21.

**Comment by GabSan1212** [comment]
> Change Enabled to True at #20 and Enabled to False at #21.

Anything else?

**Comment by aleixsr** [comment]
> > Change Enabled to True at #20 and Enabled to False at #21.
> 
> Anything else?

Restart and try :)

**Comment by GabSan1212** [comment]
> > > Change Enabled to True at #20 and Enabled to False at #21.
> > 
> > 
> > Anything else?
> 
> Restart and try :)

When im playing minecraft (for example) i get like 60-80 unestable fps with this config, do you know why?
