### ISSUE TITLE
Can Vanilla support AMD-V (SVM)?

### ISSUE THREAD

**Issue by tylinux** [AMD-OSX/bugtracker#70]
I installed macOS 10.14.4 on my Ryzen 1700 device via Valilla. Everything is perfect except Virtual Machine.VirtualBox is usable but bad performance。 I confirm that SVM support is turned on in the BIOS setup，but the output of `sysctl machdep.cpu.features` command don't contain 'svm'. Is there any way to support it ?

**Comment by williamcorney** [comment]
Is there any update on this matter as of 2023.

I have a ryzen cpu which supports svm , enabled in bios , however ‘svm’ not appearing in list of cpu features and virtual box won’t launch any vms successfully .
