### ISSUE TITLE
GPU performance

### ISSUE THREAD

**Issue by FlexIDK** [AMD-OSX/bugtracker#78]
If use patch 15h_16h on Ryzen 2600(X) - GPU have full performance
After use 17h - - GPU have only 30% performance

Sample:
15h_16h - https://browser.geekbench.com/v4/compute/4337294

17h - https://browser.geekbench.com/v4/compute/4337069

**Comment by tomnic79** [comment]
Solved disabling the Fix Pat patch for TRX40 users and using this one for all the others AMD users:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd%22%3E
<plist version="1.0">
<array>
    <dict>
        <key>Base</key>
        <string></string>
        <key>Comment</key>
        <string>algrey Shaneee - mtrr_update_action - fix PAT</string>
        <key>Count</key>
        <integer>0</integer>
        <key>Enabled</key>
        <true/>
        <key>Find</key>
        <data>
        icCB4v//AP+BygAAAQC5dwIAAA==
        </data>
        <key>Identifier</key>
        <string>kernel</string>
        <key>Limit</key>
        <integer>0</integer>
        <key>Mask</key>
        <data>
        ////////D////////////////w==
        </data>
        <key>MaxKernel</key>
        <string>20.99.99</string>
        <key>MinKernel</key>
        <string>17.0.0</string>
        <key>Replace</key>
        <data>
        uXcCAAC4BgYGBroGBgYGDzAPCQ==
        </data>
        <key>ReplaceMask</key>
        <data>
        </data>
        <key>Skip</key>
        <integer>0</integer>
    </dict>
</array>
</plist>
