### ISSUE TITLE
3rd ThreadRipper support.

### ISSUE THREAD

**Issue by jasin755** [AMD-OSX/bugtracker#8]
3rd ThreadRipper support is missing.

**Comment by dhinakg** [comment]
Please update to the latest BIOS and enable DevirtualiseMmio and see if it works.

**Comment by trisongz** [comment]
We're actively working on bare metal TRX40 over here:
https://www.macos86.it/topic/3307-trx40-bare-metal-vanilla-patches-yes-it-worksbutproxmox-is-better/

Many of us have gotten 3rd Gen Threadrippers to work, including myself, but currently investigating a several root issues with shutdown/reboot.

![image](https://user-images.githubusercontent.com/4735784/90573294-b8731c00-e17b-11ea-991a-e1703d353c91.png)

**Comment by Shaneee** [comment]
TRX40 now works bare metal. Issue closed.
